import os
import sys
import csv
import pandas as pd
from datetime import datetime

# ============================================================
# SCRIPT 05 — Data Cleaning and Validation
# ============================================================

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

RAW_DIR = os.path.join(PROJECT_ROOT, 'data', 'raw')
PROCESSED_DIR = os.path.join(PROJECT_ROOT, 'data', 'processed')

def log_audit(action, status, details=""):
    log_file = os.path.join(PROJECT_ROOT, "outputs", "logs", "audit_trail.csv")
    try:
        file_exists = os.path.isfile(log_file)
        with open(log_file, mode='a', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            if not file_exists:
                writer.writerow(['Timestamp', 'Script', 'Action', 'Status', 'Details'])
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            writer.writerow([timestamp, '05_clean_and_validate.py', action, status, details])
    except Exception:
        pass

def print_header():
    print("=" * 65)
    print("  SCRIPT 05 — Data Cleaning, Validation, & Transformation")
    print("=" * 65)
    print()

def clean_physician_and_billing():
    print("[STEP 1] Cleaning CMS Physician & Billing Data...")
    
    file_path = os.path.join(RAW_DIR, 'cms_physician', 'cms_urology_data.csv')
    if not os.path.exists(file_path):
        print(f"  ERROR: Could not find {file_path}")
        return
        
    # Read the raw CMS data
    df = pd.read_csv(file_path, low_memory=False)
    initial_rows = len(df)
    
    # 1. Handle missing values & format columns safely
    numeric_cols = ['Tot_Srvcs', 'Tot_Benes', 'Avg_Sbmtd_Chrg', 'Avg_Mdcr_Alowd_Amt', 'Avg_Mdcr_Pymt_Amt']
    for col in numeric_cols:
        if col in df.columns:
            # CMS data occasionally includes strings with commas for large numbers
            if df[col].dtype == object:
                df[col] = df[col].str.replace(',', '').astype(float)
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0.0)

    # Calculate Total Revenue generated by procedure
    df['Calculated_Total_Medicare_Payment'] = df['Tot_Srvcs'] * df['Avg_Mdcr_Pymt_Amt']
    
    # CMS data usually lacks direct RVU per line, but we can estimate RVU simply 
    # based on standard Medicare conversion factor (~$34.60 per RVU in 2022)
    df['Estimated_Total_RVUs'] = df['Calculated_Total_Medicare_Payment'] / 34.6062

    # Split into Relational Tables: Physician Table & Billing Table
    
    # --- PHYSICIAN DEMOGRAPHICS ---
    print("  Extracting unique urologists...")
    physician_cols = ['Rndrng_NPI', 'Rndrng_Prvdr_First_Name', 'Rndrng_Prvdr_Last_Org_Name', 
                      'Rndrng_Prvdr_Crdntls', 'Rndrng_Prvdr_City', 'Rndrng_Prvdr_State_Abrvtn', 'Rndrng_Prvdr_Zip5']
    physician_cols = [c for c in physician_cols if c in df.columns]
    
    df_physician = df[physician_cols].drop_duplicates(subset=['Rndrng_NPI'])
    
    out_physician = os.path.join(PROCESSED_DIR, 'physician_clean.csv')
    df_physician.to_csv(out_physician, index=False)
    
    # --- BILLING & PROCEDURES ---
    print("  Extracting pure procedure & billing lines...")
    billing_cols = ['Rndrng_NPI', 'HCPCS_Cd', 'HCPCS_Desc', 'Place_Of_Srvc', 
                    'Tot_Srvcs', 'Tot_Benes', 'Avg_Sbmtd_Chrg', 'Avg_Mdcr_Pymt_Amt', 
                    'Calculated_Total_Medicare_Payment', 'Estimated_Total_RVUs']
    billing_cols = [c for c in billing_cols if c in df.columns]

    df_billing = df[billing_cols].copy()
    # Filter out anything with 0 services to clean up garbage data
    if 'Tot_Srvcs' in df_billing.columns:
        df_billing = df_billing[df_billing['Tot_Srvcs'] > 0]
        
    out_billing = os.path.join(PROCESSED_DIR, 'billing_clean.csv')
    df_billing.to_csv(out_billing, index=False)
    
    log_audit("Clean CMS Data", "SUCCESS", f"Processed {initial_rows} into Physicians & Billing")
    print(f"  SUCCESS: Exported {len(df_physician):,} Physicians and {len(df_billing):,} Billing lines.")


def clean_hospital_benchmarks():
    print("\n[STEP 2] Cleaning Hospital Compare Benchmarks...")
    
    file_path = os.path.join(RAW_DIR, 'cms_hospital', 'hospital_general_information.csv')
    if not os.path.exists(file_path):
        print(f"  WARNING: Could not find {file_path}. Skipping.")
        return
        
    df = pd.read_csv(file_path, low_memory=False)
    
    # Filter out non-responses for 'Hospital overall rating'
    if 'hospital_overall_rating' in df.columns:
        df = df[df['hospital_overall_rating'].isin(['1', '2', '3', '4', '5'])]
        
    # Select key benchmarking metrics safely
    keep_cols = ['facility_id', 'facility_name', 'state', 'hospital_type', 'hospital_overall_rating', 
                 'mort_group_measure_count', 'safety_group_measure_count']
    keep_cols = [c for c in keep_cols if c in df.columns]
    df_benchmarks = df[keep_cols]
    
    out_bench = os.path.join(PROCESSED_DIR, 'benchmarks_clean.csv')
    df_benchmarks.to_csv(out_bench, index=False)
    
    log_audit("Clean Benchmarks", "SUCCESS", f"Processed {len(df_benchmarks)} valid hospitals")
    print(f"  SUCCESS: Exported {len(df_benchmarks):,} cleanly rated hospitals for national benchmarking.")

def verify_manual_files():
    print("\n[STEP 3] Verifying Manual Datasets (HCUP & MEPS)...")
    
    hcup_path = os.path.join(RAW_DIR, 'hcup', 'hcup_inpatient_data.csv')
    meps_path = os.path.join(RAW_DIR, 'meps', 'meps_access_data.csv')
    
    hcup_exists = os.path.exists(hcup_path)
    meps_exists = os.path.exists(meps_path)
    
    if not hcup_exists:
        print("  NOTICE: HCUP Inpatient data is missing. It will be excluded from the master database until manually added.")
    else:
        print("  SUCCESS: HCUP file located for capacity module.")
        
    if not meps_exists:
        print("  NOTICE: MEPS Access data is missing. It will be excluded from the master database until manually added.")
    else:
        print("  SUCCESS: MEPS file located for capacity module.")

if __name__ == "__main__":
    print_header()
    os.makedirs(PROCESSED_DIR, exist_ok=True)
    
    clean_physician_and_billing()
    clean_hospital_benchmarks()
    verify_manual_files()
    
    print("\n=================================================================")
    print(" SCRIPT 05 COMPLETE — READY FOR SCRIPT 06 (DATABASE LOAD)")
    print("=================================================================")
